name: useEyeDropper

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        registry-url: 'https://registry.npmjs.org'
    - name: Deploy Info
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Install
      run: yarn install
    - name: Build
      run: yarn build
    - name: Publish
      if: startsWith(github.ref, 'refs/tags/')
      run: yarn publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
  test:
    name: Unit Tests
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Test
      run: yarn test
  build-demo:
    name: Build Site
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Install Production
      run: yarn install --prod
    - name: Install Demo
      run: yarn --cwd demo install
    - name: Build Demo
      run: yarn --cwd demo build
    - name: Publish Demo
      uses: JamesIves/github-pages-deploy-action@4.1.5
      if: startsWith(github.ref, 'refs/tags/')
      with:
        branch: gh-pages
        folder: demo/out
        commit-message: Updates
  test-demo:
    name: Integration Tests
    needs: build-demo
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Test
      run: yarn --cwd demo test:ci
